"use client";

import { useEffect, useState } from "react";

import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

export default function AuditPage() {

  const [currency, setCurrency] = useState("$");

  const [tools, setTools] = useState([
    {
      tool: "ChatGPT",
      spend: "",
      teamSize: "",
    },
  ]);

  // LOAD SAVED DATA
  useEffect(() => {
    const savedTools = localStorage.getItem("tools");
    const savedCurrency = localStorage.getItem("currency");

    if (savedTools) {
      setTools(JSON.parse(savedTools));
    }

    if (savedCurrency) {
      setCurrency(savedCurrency);
    }
  }, []);

  // SAVE DATA
  useEffect(() => {
    localStorage.setItem("tools", JSON.stringify(tools));
    localStorage.setItem("currency", currency);
  }, [tools, currency]);

  // ADD TOOL
  const addTool = () => {
    setTools([
      ...tools,
      {
        tool: "Claude",
        spend: "",
        teamSize: "",
      },
    ]);
  };

  // REMOVE TOOL
  const removeTool = (index: number) => {
    const updated = tools.filter((_, i) => i !== index);
    setTools(updated);
  };

  // UPDATE TOOL
  const updateTool = (
    index: number,
    field: string,
    value: string
  ) => {
    const updated = [...tools];

    updated[index] = {
      ...updated[index],
      [field]: value,
    };

    setTools(updated);
  };

  // CALCULATIONS
  let totalSavings = 0;

  const recommendations = tools.map((item) => {

    let recommendation = "";
    let savings = 0;

    if (
      item.tool === "ChatGPT" &&
      Number(item.teamSize) <= 2 &&
      Number(item.spend) > 40
    ) {
      recommendation = "Switch to ChatGPT Plus";
      savings = Number(item.spend) - 40;
    }

    if (
      item.tool === "Cursor" &&
      Number(item.teamSize) <= 3 &&
      Number(item.spend) > 20
    ) {
      recommendation = "Downgrade to Cursor Pro";
      savings = Number(item.spend) - 20;
    }

    if (
      item.tool === "Claude" &&
      Number(item.spend) > 30
    ) {
      recommendation = "Consider lower Claude tier";
      savings = Number(item.spend) - 30;
    }

    if (
      item.tool === "GitHub Copilot" &&
      Number(item.spend) > 19
    ) {
      recommendation = "Use individual Copilot plan";
      savings = Number(item.spend) - 19;
    }

    totalSavings += savings;

    return {
      recommendation,
      savings,
    };
  });

  const yearlySavings = totalSavings * 12;

  // CHART DATA
  const chartData = tools.map((item) => ({
    name: item.tool,
    value: Number(item.spend) || 0,
  }));

  // COLORS
  const COLORS = [
    "#06b6d4",
    "#22c55e",
    "#f59e0b",
    "#ef4444",
    "#8b5cf6",
  ];

  // AI SCORE
  const aiScore =
    totalSavings > 0
      ? Math.min(
          100,
          Math.round(
            (totalSavings /
              (tools.reduce(
                (acc, item) =>
                  acc + Number(item.spend || 0),
                0
              ) || 1)) *
              100
          )
        )
      : 100;

  // TOTAL SPEND
  const totalSpend = tools.reduce(
    (acc, item) => acc + Number(item.spend || 0),
    0
  );

  // MOST EXPENSIVE TOOL
  const highestTool = tools.reduce(
    (prev, current) =>
      Number(prev.spend || 0) >
      Number(current.spend || 0)
        ? prev
        : current,
    tools[0]
  );

  // SUMMARY
  const auditSummary = `
You are currently using ${tools.length} AI tools.
You could save ${currency}${yearlySavings}
per year by optimizing subscriptions.
`;

  // DOWNLOAD REPORT
  const downloadReport = () => {

    const report = `
AI SPEND AUDIT REPORT

--------------------------------

Active Tools: ${tools.length}

Total Monthly Spend: ${currency}${totalSpend}

Monthly Savings: ${currency}${totalSavings}

Annual Savings: ${currency}${yearlySavings}

AI Efficiency Score: ${aiScore}/100

Highest Spending Tool: ${highestTool.tool}

Summary:
${auditSummary}

--------------------------------
Generated by AI Spend Audit Dashboard
`;

    const blob = new Blob(
      [report],
      { type: "text/plain" }
    );

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "ai-audit-report.txt";

    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <main
      className="min-h-screen text-white px-6 py-20 bg-cover bg-center bg-fixed"
      style={{
        backgroundImage:
          "url('https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2070&auto=format&fit=crop')",
      }}
    >

      <div className="min-h-screen bg-black/70 backdrop-blur-sm rounded-[40px] p-6">

        {/* HERO */}
        <div className="text-center max-w-5xl mx-auto">

          <h1 className="text-7xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white to-cyan-400">
            AI Spend Audit Dashboard
          </h1>

          <p className="text-zinc-300 mt-5 text-lg">
            Track and optimize your AI subscription spending
          </p>

        </div>

        {/* MAIN */}
        <div className="max-w-5xl mx-auto mt-16 space-y-8 bg-black/50 p-8 rounded-[40px] border border-white/10">

          {/* CURRENCY SELECTOR */}
          <div className="bg-zinc-900 p-6 rounded-3xl">

            <p className="mb-3 text-zinc-300 font-semibold">
              Select Currency
            </p>

            <select
              value={currency}
              onChange={(e) => setCurrency(e.target.value)}
              className="w-full p-3 bg-black border border-zinc-700 rounded-xl"
            >
              <option value="$">USD ($)</option>
              <option value="₹">INR (₹)</option>
              <option value="€">Euro (€)</option>
              <option value="£">Pound (£)</option>
              <option value="¥">Yen (¥)</option>
            </select>

          </div>

          {/* STATS */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">

            <div className="bg-zinc-900 p-6 rounded-3xl">
              <p className="text-zinc-400">
                Active Tools
              </p>

              <h2 className="text-4xl font-bold mt-2">
                {tools.length}
              </h2>
            </div>

            <div className="bg-zinc-900 p-6 rounded-3xl">
              <p className="text-zinc-400">
                Total Spend
              </p>

              <h2 className="text-4xl font-bold text-red-400 mt-2">
                {currency}{totalSpend}
              </h2>
            </div>

            <div className="bg-zinc-900 p-6 rounded-3xl">
              <p className="text-zinc-400">
                Monthly Savings
              </p>

              <h2 className="text-4xl font-bold text-green-400 mt-2">
                {currency}{totalSavings}
              </h2>
            </div>

            <div className="bg-zinc-900 p-6 rounded-3xl">
              <p className="text-zinc-400">
                Annual Savings
              </p>

              <h2 className="text-4xl font-bold text-green-400 mt-2">
                {currency}{yearlySavings}
              </h2>
            </div>

          </div>

          {/* AI SCORE + CHART */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

            {/* AI SCORE */}
            <div className="bg-zinc-900 p-6 rounded-3xl">

              <p className="text-zinc-400">
                AI Efficiency Score
              </p>

              <h2 className="text-6xl font-black text-cyan-400 mt-4">
                {aiScore}/100
              </h2>

              <div className="w-full bg-zinc-800 rounded-full h-4 mt-6">

                <div
                  className="bg-cyan-400 h-4 rounded-full"
                  style={{
                    width: `${aiScore}%`,
                  }}
                />

              </div>

              <p className="text-zinc-400 mt-5 text-sm">
                Higher score means better optimized spending.
              </p>

            </div>

            {/* PIE CHART */}
            <div className="bg-zinc-900 p-6 rounded-3xl">

              <p className="text-zinc-400 mb-4">
                Spending Breakdown
              </p>

              <div className="h-[250px]">

                <ResponsiveContainer width="100%" height="100%">

                  <PieChart>

                    <Pie
                      data={chartData}
                      dataKey="value"
                      outerRadius={90}
                      label
                    >

                      {chartData.map((_, index) => (

                        <Cell
                          key={index}
                          fill={
                            COLORS[index % COLORS.length]
                          }
                        />

                      ))}

                    </Pie>

                    <Tooltip />

                  </PieChart>

                </ResponsiveContainer>

              </div>

            </div>

          </div>

          {/* TOOL CARDS */}
          {tools.map((item, index) => (

            <div
              key={index}
              className="bg-zinc-900 p-6 rounded-3xl space-y-4"
            >

              <div className="flex justify-between items-center">

                <h2 className="text-2xl font-bold">
                  Tool {index + 1}
                </h2>

                {/* REMOVE BUTTON */}
                {tools.length > 1 && (
                  <button
                    onClick={() => removeTool(index)}
                    className="text-red-400 border border-red-400 px-3 py-1 rounded-lg text-sm hover:bg-red-500 hover:text-white transition"
                  >
                    Remove
                  </button>
                )}

              </div>

              <select
                value={item.tool}
                onChange={(e) =>
                  updateTool(index, "tool", e.target.value)
                }
                className="w-full p-3 bg-black border border-zinc-700 rounded-xl"
              >
                <option>ChatGPT</option>
                <option>Claude</option>
                <option>Cursor</option>
                <option>Gemini</option>
                <option>GitHub Copilot</option>
              </select>

              <input
                type="number"
                placeholder="Monthly Spend"
                value={item.spend}
                onChange={(e) =>
                  updateTool(index, "spend", e.target.value)
                }
                className="w-full p-3 bg-black border border-zinc-700 rounded-xl"
              />

              <input
                type="number"
                placeholder="Team Size"
                value={item.teamSize}
                onChange={(e) =>
                  updateTool(index, "teamSize", e.target.value)
                }
                className="w-full p-3 bg-black border border-zinc-700 rounded-xl"
              />

              <div className="bg-black/40 p-4 rounded-2xl border border-zinc-700">

                <p className="text-green-400 font-semibold">
                  {recommendations[index]?.recommendation || "Optimized"}
                </p>

                <p className="text-zinc-400 text-sm mt-2">
                  Savings:
                  {" "}
                  {currency}
                  {recommendations[index]?.savings}
                  /month
                </p>

              </div>

            </div>

          ))}

          {/* TOP TOOL */}
          <div className="bg-zinc-900 p-6 rounded-3xl">

            <p className="text-zinc-400">
              Highest Spending Tool
            </p>

            <h2 className="text-3xl font-bold text-red-400 mt-3">
              {highestTool.tool}
            </h2>

            <p className="text-zinc-400 mt-2">
              Current Spend:
              {" "}
              {currency}
              {highestTool.spend || 0}
            </p>

          </div>

          {/* BUTTONS */}
          <button
            onClick={addTool}
            className="w-full bg-white text-black py-4 rounded-2xl font-bold hover:scale-105 transition"
          >
            + Add Tool
          </button>

          <button
            onClick={downloadReport}
            className="w-full bg-green-500 text-black py-4 rounded-2xl font-bold hover:scale-105 transition"
          >
            Download Report
          </button>

          {/* SUMMARY */}
          <div className="bg-cyan-500/10 border border-cyan-500/20 p-6 rounded-3xl">

            <h2 className="text-2xl font-bold">
              AI Audit Summary
            </h2>

            <p className="text-zinc-300 mt-4 leading-8">
              {auditSummary}
            </p>

          </div>

        </div>
      </div>
    </main>
  );
}